### ISSUE TITLE
Index specific event from all contracts

### ISSUE THREAD

**Issue by YasseinBilal** [enviodev/hyperindex#118]
Hi, 
Is there currently away to index all events with specific signature regardless which contract emits them. This is currently doable in the graph protocol by not specifying the source contract. Is there away to achieve that in HyperIndex?

Thanks

**Comment by moose-code** [comment]
We've spec'd this out and hope to have it implemented soon 👍 Although we haven't agreed on an exact timeline so @JonoPrest would maybe know better where it falls in the realm of things. 

Currenly you can achieve similar functionlity with HyperSync (fetching all events just by signature) using our node python or rust client. https://docs.envio.dev/docs/HyperSync/overview

**Comment by moose-code** [comment]
This feature is busy being developed now! @YasseinBilal - what is your timeline?

**Comment by YasseinBilal** [comment]
@moose-code It would be nice if we could have it during the next 1 or 2 weeks

**Comment by JasoonS** [comment]
@YasseinBilal - here is a discussion if you have specific requirements: https://github.com/enviodev/hyperindex/discussions/123#discussion-7059092

We can't make promises on the timeline, but we will do it as fast as we can without sacrificing quality :)

**Comment by moose-code** [comment]
@YasseinBilal We are close with this!

**Comment by moose-code** [comment]
Hi @YasseinBilal - we've had some bugs performance regressions we've prioritized which has delayed the timeline, but we are super close with this. @JonoPrest almost has it all ready. Sometime next week you should be able to get involved :)

**Comment by YasseinBilal** [comment]
Thanks @moose-code

**Comment by moose-code** [comment]
Hi @YasseinBilal - this is completed!! https://github.com/enviodev/hyperindex/releases/tag/v2.3.0

Please take it for a spin and let us know how it goes :)
