### ISSUE TITLE
Events processed discrepency [v1.3.1 and v2.1.2 hosted service]  (possible, needs investigation)

### ISSUE THREAD

**Issue by moose-code** [enviodev/hyperindex#167]
We are investigating a discrepenacy observered on the hosted service where it would appear that between versions v1.3.1 and v2.1.2 a different amount of events are processed on a particular indexer. 

We are actively trying to reproduce to understand where this discrepency stems from as it could be many things (user differences in code, hosted service, reorg mode, v2 changes etc).

![Screenshot 2024-09-03 at 11 01 40](https://github.com/user-attachments/assets/923a9dd9-53f9-4553-8507-2b41c296096f)
![Screenshot 2024-09-03 at 11 01 48](https://github.com/user-attachments/assets/b3f93999-6487-49da-8805-e73ffdd2fbcf)

**Comment by JonoPrest** [comment]
@moose-code, I'm going to close this since we discovered the crash/restart bug with dynamic contracts which likely lead to the data discrepency.
