### ISSUE TITLE
Float from indexer is returned as numeric field 

### ISSUE THREAD

**Issue by moose-code** [enviodev/hyperindex#187]
![Screenshot 2024-09-09 at 16 50 41](https://github.com/user-attachments/assets/ee9a398a-fdc9-4d01-8f8c-ece86bb46b20)
![Screenshot 2024-09-09 at 16 51 05](https://github.com/user-attachments/assets/e155a2d0-78ba-477f-b51a-24de0fd9509b)

**Comment by JonoPrest** [comment]
Lets investigate if we can configure Hasura to use our own scalar definitions.

**Comment by JonoPrest** [comment]
@Simon0x to answer the question why is it returned as a numeric. This is because Javascript floats will exceed the size limit of postgres floats. So we use numeric to store them. But we do have BigDecimal now so maybe if we bump into those issues we can just point people to using BigDecimal
