### ISSUE TITLE
Error while Update ContractURISet event field with indexed

### ISSUE THREAD

**Issue by saiSunkari19** [enviodev/hyperindex#195]
**Describe the bug**

I am working on implementing the beacon proxy for the NFT Factory.  I have implemented an implementation contract for proxies. 
In the implementation contract, I have the `ContractURISet` event, which will be emitted when the collection owner updates the contract uri. 
During the initial version I added `ContractURISet(string indexed URI)`, because of the indexed string, I got the hexa value, not the URI string. 

![photo_2024-09-13 16 24 11](https://github.com/user-attachments/assets/8b3f8639-638c-4d8e-a666-125c40a4f28d)
 

Then, I updated my implementation contract to remove the index from the ContractURISet event. now with the new implementation contract it contains` ContractURISet(string URI)`.

**To Reproduce**
1. I have updated the new implementation abi in our envio abis list. 
2. When I start the indexer, it shows that the data file has empty bytes. 

![photo_2024-09-13 16 27 20](https://github.com/user-attachments/assets/02ee85ab-4930-4653-908f-eebac09a3ba2)

**Screenshots**

**Local (please complete the following information):**
 - Envio version - 2.1.2
 - Node version - v18.19.0
 - pnpm version - 
 - Docker version (if running locally)

**Hosted Service (please complete the following information):**
 - Envio version
 - Link to the deployed indexer

**Additional context**

**Comment by moose-code** [comment]
Hi @saiSunkari19 - can you please use the latest envio version, v2.2.3 and see if the problem persists?

**Comment by saiSunkari19** [comment]
> Hi @saiSunkari19 - can you please use the latest envio version, v2.2.3 and see if the problem persists?

<img width="955" alt="image" src="https://github.com/user-attachments/assets/6202a8dc-94e7-4710-8904-f68f73d74993">

@moose-code  no luck

**Comment by saiSunkari19** [comment]
@moose-code  any update on this?

**Comment by JonoPrest** [comment]
Hey @saiSunkari19,

I have it on my list to look at this. Currently I can't think of a simple work as is and to handle this properly will require some additional implementation/checks.

**Comment by saiSunkari19** [comment]
> Hey @saiSunkari19 when this PR is merged and released: #204
> 
> You can define your two versions of the same event on your contract and alias the one with a different name like this:
> 
> ```yaml
>         events:
>           - event: "ContractURISet(string indexed URI)"
>             name: "ContractURISetIndexed"
>           - event: "ContractURISet(string URI)"
>             name: "ContractURISetNotIndexed"
> ```
> 
> You will need to register a handler for both of them but you should be able pass the same handler to both. You just need to make sure they have a different name. So you can alias just the one if you like.

Sure, I will check that

**Comment by JonoPrest** [comment]
> Do I need to give both versions of abi files, can give me an examples?

Hey @saiSunkari19, sorry I didn't see your question before. I would suggest just inline the signature of the event like in the example I gave. Or you will need to compile an ABI with both signatures but it will be easiest if you just annotate the signature explicitly.
