### ISSUE TITLE
Duplicate key value violates unique constraint "entity_history_pkey"

### ISSUE THREAD

**Issue by 0xKrauser** [enviodev/hyperindex#205]
**Describe the bug**
After introducing a wildcard instance to our codebase we clash with this error close to the end of the synchronization process.
The problem seems to be the coexistence of a wildcard handler as well as a `contractRegister` for a contract that is also capable of emitting the event that is monitored with the wildcard.
Removing `contractRegister` makes the indexer sync correctly
Removing the wildcard event makes the indexer sync correctly

```
msg: "Failed writing batch to database"
first-event-timestamp: 1725728845
error: {"type":"PostgresError","message":"duplicate key value violates unique constraint \"entity_history_pkey\"","stack_trace":"PostgresError: duplicate key value violates unique constraint \"entity_history_pkey\"\n at ErrorResponse (/app/base-template/node_modules/.pnpm/postgres@3.4.1/node_modules/postgres/cjs/src/connection.js:783:26)\n at handle (/app/base-template/node_modules/.pnpm/postgres@3.4.1/node_modules/postgres/cjs/src/connection.js:475:6)\n at TLSSocket.data (/app/base-template/node_modules/.pnpm/postgres@3.4.1/node_modules/postgres/cjs/src/connection.js:315:9)\n at TLSSocket.emit (node:events:519:28)\n at TLSSocket.emit (node:domain:488:12)\n at addChunk (node:internal/streams/readable:559:12)\n at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n at TLSSocket.Readable.push (node:internal/streams/readable:390:5)\n at TLSWrap.onStreamRead (node:internal/stream_base_commons:191:23)\n at cachedError (/app/base-template/node_modules/.pnpm/postgres@3.4.1/node_modules/postgres/cjs/src/query.js:170:23)\n at new Query (/app/base-template/node_modules/.pnpm/postgres@3.4.1/node_modules/postgres/cjs/src/query.js:36:24)\n at sql (/app/base-template/node_modules/.pnpm/postgres@3.4.1/node_modules/postgres/cjs/src/index.js:112:11)\n at Object.module.exports.batchInsertEntityHistory (/app/base-template/generated/src/db/DbFunctionsImplementation.js:273:14)"}
```

**To Reproduce**

1. [Clone reproduction repo](https://github.com/0xKrauser/postgres-error-minimal)
2. Launch `envio dev` with latest envio version (2.3.0 current)
3. Wait for sync to fail
4. Check logs for this error.
The logs also report other errors for operations in the same batch, but this should be the one making it fail

**Expected behavior**
Being able to have both the wildcard event and the handleRegistration event for a contract that is also indexed by the wildcard.
Primary keys not to clash and complete sync without throwing.

**Local (please complete the following information):**
 - Envio version: 2.3.0
 - Node version: 20.15.1
 - pnpm version: 9.5.0
 - Docker version: 26.1.4-1, build 5650f9b10226d75e8e9a490a31cc3e5b846e0034

**Hosted Service (please complete the following information):**
 - Envio version: 2.3.0
 - Link to the original deployed indexer: https://envio.dev/app/beramarket/torchbearer/4e13dca
 - Link to minimal reproduction deployed indexer: https://envio.dev/app/0xkrauser/postgres-error-minimal/3192a20

**Additional context**
I experience this problem both on GitHub Codespaces (Ubuntu) as well in local using WSL (Windows 11).

**Comment by moose-code** [comment]
> Being able to have both the wildcard event and the handleRegistration event for a contract that is also indexed by the wildcard.


Is the second limitation here perhaps your issue? https://docs.envio.dev/docs/HyperIndex/wildcard-indexing
<img width="739" alt="Screenshot 2024-09-16 at 17 08 55" src="https://github.com/user-attachments/assets/41bd221a-a514-4a51-82b0-f14c3b9849da">

**Comment by 0xKrauser** [comment]
> > Being able to have both the wildcard event and the handleRegistration event for a contract that is also indexed by the wildcard.
> 
> Is the second limitation here perhaps your issue? https://docs.envio.dev/docs/HyperIndex/wildcard-indexing <img alt="Screenshot 2024-09-16 at 17 08 55" width="739" src="https://private-user-images.githubusercontent.com/20556729/367835032-41bd221a-a514-4a51-82b0-f14c3b9849da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1MDU2NjMsIm5iZiI6MTcyNjUwNTM2MywicGF0aCI6Ii8yMDU1NjcyOS8zNjc4MzUwMzItNDFiZDIyMWEtYTUxNC00YTUxLTgyYjAtZjE0YzNiOTg0OWRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE2VDE2NDkyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4ZGEwZTc4N2E1NGNkMGE2OGQ1ZDU4YTg3ZjBlNzhmOWFjYTU2ZmI3MmJkYjY0MWY1OTAxNmY3NmQ5YTc5NDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5_i7E5vp7v57pvSF_ApnI1pudF7GDgJYOaOUT5-6yCA">

If I understand correctly, I don't think that's the case, in my case there's a `<event1>.handler` with wildcard event config, and an `<event2>.contractRegister` without event config object and listening to only one specific address as you can see from the minimal reproduction repo.

So, two different events, and one is with wildcard and one isn't. Doesn't respect both of the requirements for that limitation.

**Comment by JonoPrest** [comment]
Hey @0xKrauser, when I clone your repo and run:

```
pnpm install
pnpm envio dev
```
The indexer doesn't crash with the error as you've described but it does appear stuck. 

![Screenshot 2024-09-17 at 13 17 54](https://github.com/user-attachments/assets/7b3f74e5-a3f9-4db1-99af-c8eeb876c7c6)

Does your local indexer get passed 3425 events when it crashes?

**Comment by 0xKrauser** [comment]
Yes, it goes past that, it usually crashes around the 3,700,000 mark iirc.
You can also check the logs of the hosted service.

**Comment by JonoPrest** [comment]
Hey @0xKrauser,

Thanks for reporting. I did manage to reproduce the crash and it is indeed a bug that should be fixed by this https://github.com/enviodev/hyperindex/pull/210
