### ISSUE TITLE
Expected entities not in db

### ISSUE THREAD

**Issue by DenhamPreen** [enviodev/hyperindex#240]
**Describe the bug**
Expected entities to be created which are not found in the production deployment on the hosted service. Running it locally with a modified start and end block and the entities appear. 
It fits the experience of the effects of a reorg however seems unlikely since it's in succession. 

**Expected behavior** / **To Reproduce**

* I am unable to replicate the behaviour locally, I havn't run it from startblock 0 since it has 30mil events and will take ~18 hours.
* When indexing locally the entities are indexed, note this is with a more recent start block 

For all queries perform them here on this prod deployment
https://envio.dev/app/gnosis/wallet-indexer/61f0300/playground

For this Safe: https://gnosisscan.io/address/0xF35128804511Ef5c98D3b539592C88e0928bdfA3

We expect to see the last 5 tx's starting with 
https://gnosisscan.io/tx/0xc46fc8f4c9439366e449d0cc89881e32de202b402614687afd7fc8f23f46c2f8
as Metri_Transaction entities in the indexer

```graphql
query allTransactions {
  Metri_Transaction(
    where: {id: {_eq: "0xc46fc8f4c9439366e449d0cc89881e32de202b402614687afd7fc8f23f46c2f8"}}
  ) {
    id
  }
}```
- tx - 0xb993e4baea227f7423998fa26164788ee95f32648a19598911fe88d2106ab216 
- tx - 0xb3a54e49262a2279ed8058a8a4626cac957a70a3b2dd583fdd50abe00e9a19d1
- tx - 0xc46fc8f4c9439366e449d0cc89881e32de202b402614687afd7fc8f23f46c2f8

(This Metri_Transaction entity is showing - 0xb97258fd89140b46be39e6b4753480074fdf3545658b1465cbb8b543e6b39b04 its much more recent)

Interestingly the 6th tx which is 10 days ago at this time is in the indexer
```graphql
query allTransactions {
  Metri_Transaction(
    where: {id: {_eq: "0x7587875c5b85d648b57e48430ef463542a9332369e8dedefb529b2963e764136"}}
  ) {
    id
  }
}
```

the contract in question is dynamically registered and we know from the above query that it is indexing at some point
```
query allTransactions {
  dynamic_contract_registry(
    where: {contract_address: {_eq: "0xF35128804511Ef5c98D3b539592C88e0928bdfA3"}}
  ) {
    contract_type
  }
}
```

The indexer is not stuck we can validate this from this query which you can cross reference with this block number https://gnosisscan.io/
```graphql
query allTransactions {
  chain_metadata {
    latest_processed_block
  }
}
```

**Local (please complete the following information):**
 - Envio version - 2.2.3
 - Node version - 18.18.2
 - pnpm version - 9.1.1
 - Docker version - 25.0.3, build 4debf41

**Hosted Service:**
 - Envio v2.2.3
 - https://envio.dev/app/gnosis/wallet-indexer/61f0300/

**Additional context**
- Indexer has a very high number of contracts it's indexing (partitioning relevant)
- The indexer was deployed 17 days ago and the skipped creation of entities occurring 2/3 days ago , ie at the head indexing

**Comment by JonoPrest** [comment]
Hey @DenhamPreen, I've been looking at this indexer and I suspect this is due to the dynamic contracts bug that was fixed in 2.4.4

I'll close for now and if we have any more issues we'll look again.
