### ISSUE TITLE
Dynamic contract is pausing other indexing.

### ISSUE THREAD

**Issue by siddharth9903** [enviodev/hyperindex#248]
**Describe the bug**
Didn't index fully, still showing synced and not having expected indexed data.

<img width="447" alt="Screenshot_2024-10-02_at_9 03 31_PM" src="https://github.com/user-attachments/assets/3c6659f8-1ac3-4d77-89e9-3dd6d3b4053b">
It's showing synced but indexed data is upto 20,541,836 instead of 20,541,837.

**To Reproduce**
This could be very edge to reproduce, my context was
I was indexing 2 factory contracts and both of which is indexing tokenCreated event which is registering new BondingCurve contract dynamically for indexing. if first bondingCurve contract hasn't fired any event then it all stuck there. It won't even index further tokenCreated even of Factory2 contract which isn't even dynamic.
To give clear context,

Indexing FactoryContract1 and FactoryContract2,

Block              | Contract.      | Event
---------------------------------------------
20,541,836    | Factory1                  | tokenCreated (token1, bondingCurve1)  //registering dynamic contract to index
20,541,837    | Factory2                  | tokenCreated (token2, bondingCurve2) //registering dynamic contract to index

It's getting stuck at 20,541,836 block and not even indexing Factory2 tokenCreated event

It's working when dynamically registered bondingCurve has emitted events, 
It's working in following example.

Block              | Contract.      | Event
---------------------------------------------
20,541,836    | Factory1                  | tokenCreated (token1, bondingCurve1)  //registering dynamic contract to index
20,541,837    | Factory2                  | tokenCreated (token2, bondingCurve2) //registering dynamic contract to index
20,541,838    | bondingCurve1       | buyToken ()
20,541,839    | bondingCurve2       | buyToken ()

Here it's indexing every data(expected behaviour)

I couldn't give you exact code as it's private.

**Comment by JasoonS** [comment]
Is it possible that Bonding Curve 1 has many millions of events in it before Bonding Curve 2 and the indexer needs to process all of them or does it completely get stuck even if you wait for a few minutes?

**Comment by siddharth9903** [comment]
No, it wasn't millions of event, it's only 1 event still I waited few minutes. so, it was fully stucked and shown synced.

**Comment by JonoPrest** [comment]
@siddharth9903 just a bump if you could give us something to reproduce your problem. A self contained repro would be first prize.

Otherwise at least if you could share the envio version you are using, along with your config.yaml and the "contractRegister" function code you are using.

**Comment by siddharth9903** [comment]
It was somehow resolved once I updated the envio version. so it would be great if I close this issue.

**Comment by JonoPrest** [comment]
Awesome @siddharth9903, there were a couple of fixes in the last 2 weeks that could have solved this case 👍🏼
