### ISSUE TITLE
Indexing error: `eth_getLogs` uses `toBlock` less than `fromBlock`

### ISSUE THREAD

**Issue by pavlovdog** [enviodev/hyperindex#263]
**Describe the bug**
Self-hosted envio sends plenty of `eth_getLogs` RPC requests, where `fromBlock` is greater than `toBlock`.

```
{
  "log.level": "warn",
  "@timestamp": "2024-10-15T11:50:33.027Z",
  "process.pid": 17,
  "host.hostname": "primary-6c9fd6d85d-4vkxt",
  "ecs.version": "1.6.0",
  "chainId": 8333,
  "logType": "Block Range Query",
  "workerType": "RPC",
  "fromBlock": 6612024,
  "toBlock": 6612024,
  "addresses": [
    "0x5FF137D4b0FDCD49DcA30c7CF57E578a026d2789",
    "0x0000000071727De22E5E9d8BAf0edAc6f37da032"
  ],
  "fetchStateRegister": "root",
  "msg": "Error getting events, will retry after backoff time",
  "backOffMilliseconds": 5000,
  "err": {
    "RE_EXN_ID": "Promise.JsError/1",
    "_1": {
      "code": "UNKNOWN_ERROR",
      "error": {
        "code": -32000,
        "message": "invalid block range params"
      },
      "payload": {
        "method": "eth_getLogs",
        "params": [
          {
            "address": [
              "0x0000000071727de22e5e9d8baf0edac6f37da032",
              "0x5ff137d4b0fdcd49dca30c7cf57e578a026d2789"
            ],
            "topics": [
              [
                "0x49628fd1471006c1482da88028e9ce4dbb080b815c9b0344d39e5a8e6ec1419f",
                "0xd51a9c61267aa6196961883ecf5ff2da6619c37dac0fa92122513fb32c032d2d"
              ]
            ],
            "fromBlock": "0x64e438",
            "toBlock": "0x64e437"
          }
        ],
        "id": 4269,
        "jsonrpc": "2.0"
      },
      "shortMessage": "could not coalesce error"
    }
  }
}
```

**Local (please complete the following information):**
 - envio 2.4.3
 - node v20.12.1
 - pnpm 8.15.4
 - Docker 26.1.4, build 5650f9b

**Hosted Service (please complete the following information):**
 - Envio version - 2.4.3
 - https://envio.dev/app/pavlovdog/indexer-pavlovdog-2

**Additional context**
It seems to happen only when syncing network with RPC, can't find any logs related to networks which are using HyperSync.

**Comment by JonoPrest** [comment]
Hey @pavlovdog the rpc worker uses an [AIMD](https://en.wikipedia.org/wiki/Additive_increase/multiplicative_decrease) algorithm to try find the biggest block range that it can for indexing for a given RPC endpoint.

You can configure values for this search in your config.yaml file (have a look at the config explorer: https://docs.envio.dev/docs/HyperIndex/configuration-file#explorer)

![Screenshot 2024-10-17 at 12 14 58](https://github.com/user-attachments/assets/234112e4-f046-4292-9309-6ff9e99bc988)

You can set the `interval_ceiling` of the maximum block range you would like it to try. Defaults to 10,000.

**Comment by JonoPrest** [comment]
Or you can use environment variables to set these: 

https://github.com/enviodev/hyperindex/blob/b64292b0951ba33d53dc7b940d3ee6db71292362/codegenerator/cli/templates/static/codegen/src/Env.res#L94-L101

**Comment by pavlovdog** [comment]
Hey @JonoPrest ! Not sure if I understand you, my concern (according to logs) is that `toBlock` is less than `fromBlock`. These are the values from the log in the description

```
~ echo $[0x64e438]
6612024
~ echo $[0x64e437]
6612023
```

Here is another log, with the same issue

```
[03:40:21.326] TRACE (84463):
    chainId: 84532
    message: "Finished page range"
    fromBlock: 16720660
    toBlock: 16720659
    number of logs: 0
    stats: {
      "total time elapsed (ms)": 0
    }
```

Again, `fromBlock` is greater than `toBlock`. I don't think `ceiling_interval` helps here.

**Comment by JonoPrest** [comment]
> Again, `fromBlock` is greater than `toBlock`. I don't think `ceiling_interval` helps here.

@pavlovdog understood! Sorry I thought you were concerned about it continuously breaking on a query that is too large.

This definitely shouldn't happen 🤔 will look into it shortly. It should be benign in terms of data correctness but either way is wasteful and could cause unnecessary crash/restarts.

**Comment by PaulRBerg** [comment]
I implemented @JonoPrest's proposed fix (setting `interval_ceiling`) but I am still getting errors like this:

```text
[15:59:34.263] WARN (20676): Issue while running fetching batch of events from the RPC. Will wait 1000ms and try again.
    type: "EXPONENTIAL_BACKOFF"
    err: {
      "RE_EXN_ID": "JsError",
      "_1": {
        "code": "UNKNOWN_ERROR",
        "error": {
          "code": -32062,
          "message": "Block range is too large",
          "data": {
            "trace_id": "4a479dfaf5d90afd981861285e3832d5"
          }
        },
        "payload": {
          "method": "eth_getBlockByNumber",
          "params": [
            "0x1bdde1d",
            false
          ],
          "id": 138,
          "jsonrpc": "2.0"
        },
        "shortMessage": "could not coalesce error"
      }
    }
```

The error is also difficult to debug/trace because there is no information about the chain ID.

**Comment by PaulRBerg** [comment]
I don't know. See the Warp block URLs shared in https://github.com/enviodev/hyperindex/issues/603.
