### ISSUE TITLE
Query contract state at event time

### ISSUE THREAD

**Issue by akkien** [enviodev/hyperindex#267]
When process the event, I want to query token's price in USDC. With Thegraph I can query synchronously by using `Contract.bind`. With envio, I can specify RpcUrl, using web3/ethers to make rpc call. It takes time to call to fullnode and affects subgraph synchronization time.

Is there any way to support query contract state synchronously in the same way as Thegraph?

**Comment by JonoPrest** [comment]
> When process the event, I want to query token's price in USDC. With Thegraph I can query synchronously by using `Contract.bind`. With envio, I can specify RpcUrl, using web3/ethers to make rpc call. It takes time to call to fullnode and affects subgraph synchronization time.
> 
> Is there any way to support query contract state synchronously in the same way as Thegraph?

Hey @akkien, unfortunately we don't supply any apis for contract state/storage so you have to do that with RPC calls. It is indeed slow to index and it's also slow on subgraphs unfortunately. The fact that it appears "synchronous" doesn't make it any faster unfortunately. 

The best options for speed are to have a good RPC endpoint and to cache responses if you are making the same calls multiple times.

**Comment by akkien** [comment]
Hi @JonoPrest, thanks for your clarification. I'm clear now.
