### ISSUE TITLE
Bad rescript error message 

### ISSUE THREAD

**Issue by moose-code** [enviodev/hyperindex#283]
This error "Failed to seralize JSON at root. Reason: the S.transform serliazer is missing" 

has confused two different users now and doesn't provide a clear root as to the issue. 

This occured on the velodrome indexer and the rhinestone indexer. I believe @DZakh has an idea for why it occurs and a fix. 

![image](https://github.com/user-attachments/assets/75f5d674-ac7b-4d1b-8feb-6c0ced951f7b)

**Comment by moose-code** [comment]
https://github.com/rhinestonewtf/rhinestone-indexer/commit/3aac2f6b7ebd9f5bcb4360e3e856295c90dd0f9a

Happened also when things weren't correctly awaited

**Comment by JonoPrest** [comment]
Closed by https://github.com/enviodev/hyperindex/pull/297
