### ISSUE TITLE
Skips event when using preRegisterDynamicContracts option

### ISSUE THREAD

**Issue by chrisais9** [enviodev/hyperindex#286]
**Describe the bug**
Indexer skips events internally when using `preRegisterDynamicContracts` option.

(This error is intended on handler. It logs when there are no pool found when indexing event)
It shouldn't happen because every Swap, Mint, Burn events. pool must be registered and it did previously.

**This error doesn't show up in v2.4.4 and below**.

I think this is a bug with preRegisterDynamicContracts.

**To Reproduce**
1. Clone repo shared via private TG conversation.
2. Run Indexer using v2.5.0 and higher (or just latest version) with `preRegisterDynamicContracts`
3. Watch console log

**Expected behavior**
No error with clean console as v2.4.4 and below

**Screenshots**

<img width="1432" alt="123" src="https://github.com/user-attachments/assets/97c781a5-3710-4d73-9a0c-cd8f645d0d7b">

**Local (please complete the following information):**
 - Envio version: v2.5.1
 - Node version: v18.18.0
 - pnpm version: v8.6.1
 - Docker version (if running locally): v27.2.0

**Hosted Service (please complete the following information):**
 - Envio version: 
 - Link to the deployed indexer N

**Additional context**
contact with TG would be happy for furthermore infos.

**Comment by JonoPrest** [comment]
Hey @chrisais9,

I ran your indexer and noticed that the indexer was restarting twice after pre registration. This was definitely a bug fixed here: https://github.com/enviodev/hyperindex/pull/295

I will validate that this fixes your issue and if so will close once it's merged.

**Comment by JonoPrest** [comment]
@chrisais9 is it working for you? Can I close this issue?
