### ISSUE TITLE
Build fails on Hosted Service

### ISSUE THREAD

**Issue by chrisais9** [enviodev/hyperindex#300]
**Describe the bug**
Build fails on Hosted Service with latest version.

**To Reproduce**

1. Go to Hosted Service
2. Deploy indexer with envio version v2.6.0 and upper
3. See error

**Expected behavior**
Should build successful and indexing starts up.

**Screenshots**

![image](https://github.com/user-attachments/assets/6feb70e5-1ed1-4843-96ae-e71bfe0e990a)
**Local (please complete the following information):**
 - Envio version
 - Node version
 - pnpm version
 - Docker version (if running locally)

**Hosted Service (please complete the following information):**
 - Envio version 2.6.1
 - Link to the deployed indexer: https://envio.dev/app/hashscape/salt-dex-indexer-v1.0.0

**Additional context**
Builds well on self hosted environment

**Comment by chrisais9** [comment]
The error shows on my local too when I updated pnpm to v9(v9.12.2, latest). Previous version was v8
`ERR_PNPM_RECURSIVE_EXEC_FIRST_FAIL  Command "rescript" not found`

I think pnpm has problem installing dependacy inside generated folder on latest version

**Comment by DenhamPreen** [comment]
Could you share the `package.json` file here

**Comment by chrisais9** [comment]
Issue solved by adding missing pnpm-workspace.yml file. Thanks for the instructions on private chat.
