### ISSUE TITLE
Handler not saving entity properly with preRegisterDynamicContracts

### ISSUE THREAD

**Issue by chrisais9** [enviodev/hyperindex#311]
**Describe the bug**
DB INSERT command may not working properly such as `context.Bundle.set(bundle)` when `{ preRegisterDynamicContracts: true }`.

**To Reproduce**

E.g.
1. Go to https://github.com/Hashscape/salt-dex-indexer
2. Start Indexer
3. Wait for preRegistration to finish
4. See errors in TUI

**Expected behavior**
Should index properly. 
Indexes properly with `preRegisterDynamicContracts` off

**Screenshots**
<img width="441" alt="1234" src="https://github.com/user-attachments/assets/e9a2a1d0-1311-49c8-8f75-41ace4cbdfe3">
(Intended to WARN if entity doesn't exist on prev block, this case should never happen. the bundle must be created on first block and persists)

**Local (please complete the following information):**
 - Envio version 2.7.0
 - Node version v20.18.0
 - pnpm version 9.12.3
 - Docker version (if running locally) 27.3.1

**Hosted Service (please complete the following information):**
 - Envio version N/A
 - Link to the deployed indexer N/A

**Additional context**

**Comment by DenhamPreen** [comment]
Thanks @chrisais9, I think this is possibly related to this [PR](https://github.com/enviodev/hyperindex/pull/304)

Will flag internally 🙏

**Comment by chrisais9** [comment]
For more context, Bundle entity should be inserted on any event. Please refer to code below

```ts
     // create new factory if null(= on the very first event)
    if (!factory) {
      context.log.info(`Creating Factory`);

      factory = {
        id: factoryId,
        address: event.srcAddress,
        chainId: event.chainId,
        isV2: true,
        poolCount: 0n,
        totalVolumeETH: ZERO_BD,
        totalVolumeUSD: ZERO_BD,
        txCount: 0n,
        owner: ADDRESS_ZERO,
      };

      // create new bundle for tracking eth price
      context.Bundle.set({
        id: event.chainId.toString(),
        ethPriceUSD: ZERO_BD,
      });
    }
```

**Comment by JonoPrest** [comment]
@chrisais9, your master branch shows you are using envio v2.6.1:
https://github.com/Hashscape/salt-dex-indexer/blob/f3fbfda3f4e3b4a00def34021f13b709d4b20fcf/package.json#L27

Are you sure you tried with v2.7?

**Comment by chrisais9** [comment]
@JonoPrest Yes, I didn't pushed yet. I will push right away
