### ISSUE TITLE
PoolFactory Address of Aerodrome when entered in hyperindex cli, instead of poolcreated events, it shows swap, mint and other events.

### ISSUE THREAD

**Issue by fuzztobread** [enviodev/hyperindex#320]
**Describe the bug**
When entering the poolfactory address of aerodrome contract in hyperindex cli, the events emitted are swap, mint and other instead of being poolcreated since it is a factory address

**To Reproduce**

E.g.
1. Go to aerodome docs and copy the poolfactory address
2. From hyperindex, enter the address of poolfactory in base chain
3. See error

**Expected behavior**
Poolcreated events should be shown instead of swap and other.

**Comment by JonoPrest** [comment]
@fuzztobread it doesn't seem that way to me? Could you provide an address that you tried?

![Screenshot 2024-11-05 at 10 05 20](https://github.com/user-attachments/assets/266fcc7c-525e-48fa-826a-30e3c62ac3e2)

**Comment by fuzztobread** [comment]
Hi, i used [0x420DD381b31aEf6683db6B902084cB0FFECe40Da](https://basescan.org/address/0x420DD381b31aEf6683db6B902084cB0FFECe40Da) address.If you check the events emitted on basescan using the provided address, it's only create pool but when entered on hyperindex, gives different events.

**Comment by JonoPrest** [comment]
> Hi, i used [0x420DD381b31aEf6683db6B902084cB0FFECe40Da](https://basescan.org/address/0x420DD381b31aEf6683db6B902084cB0FFECe40Da) address.If you check the events emitted on basescan using the provided address, it's only create pool but when entered on hyperindex, gives different events.

Thanks! I see it's causing the problem on my side as well. Will investigate and get a fix out. In the mean time you can always use the address I used to get started and swap out the address in your config.yaml afterwards 👍🏼

**Comment by fuzztobread** [comment]
Sure thing. Thank you

**Comment by JonoPrest** [comment]
This should now be fixed 👍🏼
