### ISSUE TITLE
preset addresses in config.yml and contractRegistry used together create issues

### ISSUE THREAD

**Issue by vibern0** [enviodev/hyperindex#354]
**Describe the bug**
When using `contractRegistry` together with preset addresses in config.yml, it results in wrong data somehow.
Below are screenshots of before and after. I've changed to `contractRegistry` with `preRegisterDynamicContracts` only and the issue is gone.
The issue is last present at [here](https://github.com/gnosis/circles-envio-indexer/commit/a9cfdda545c88ddd33943beb48c2e31bdce8b9ff), and fixed [here](https://github.com/gnosis/circles-envio-indexer/commit/cadfc582dcb62e082d1b5f2b42bb19655f0fc5fe).

**To Reproduce**

E.g.
1. deploy problematic indexer and query with example query
2. observe the error
3. deploy with fixed indexer and query with example query
4. observe it's correct

Example query

```graphql
query getAvatarBalances($address: String) {
  AvatarBalance(where: {avatar_id: {_eq: $address}, balance:{_lt:0}}) {
    balance
    token {
      id
      tokenOwner {
        id
        profile {
          name
        }
        isVerified
      }
    }
  }
}
```
example address: `0x42cEDde51198D1773590311E2A340DC06B24cB37`

**Expected behavior**
I'd expect using `contractRegistry` together with preset addresses in config.yml

**Screenshots**
(with issue)
![Captura de ecrã 2024-11-21, às 21 13 05](https://github.com/user-attachments/assets/a15739b3-43fa-4795-9684-866c33ada346)
(fixed)
![Captura de ecrã 2024-11-21, às 21 13 20](https://github.com/user-attachments/assets/d11d1512-da0c-4f19-bb69-66d6b09a35af)

**Local (please complete the following information):**
 - Envio version: 2.7.4
 - Node version: 22
 - pnpm version: 9.12.3
 - Docker version (if running locally): 4.34.2

**Hosted Service (please complete the following information):**
 - Envio version: 2
 - Link to the deployed indexer: (problematic one) https://v2.hyperindex.xyz/app/gnosis/circles-envio-indexer/33406af (fixed version is in prod)

**Additional context**

**Comment by DZakh** [comment]
Thanks for creating the issue 🙏

@JonoPrest, Could you take a look when you're back? Or let me know to do it myself 👍

**Comment by DZakh** [comment]
Could you try the envio v2.9.1? We fixed an edge case for dynamic contract registration, which might be related to the one you had.

**Comment by DZakh** [comment]
Please reopen the issue if you still get the problem 👍
