### ISSUE TITLE
Non-interactive usage of CLI for a single contract/ABI/rpc

### ISSUE THREAD

**Issue by drewstone** [enviodev/hyperindex#358]
# Overview
Currently there is no way to non-interactively initialize an envio indexer, even using the `contract-import local`, you are still required to choose what language, address, whether you want to add another contract or be finished, and whether you have an envio API key.

It would be beneficial to be able to support a single CLI execution for spinning this up, so automation can be made more easily.

**Comment by DenhamPreen** [comment]
Hey @drewstone, yes it is intended to be designed that it's fully non-interactive. It's possible that features have been added without adding flags etc. 
I'll have to check specifically but I think some of the above can be input via cli args. 

To summarize your points
- language (I believe this is -l usage `pnpx envio init -l typescript`)
- address
- add another contract / finished
- envio api key

I'll check for the other fields quickly too.

**Comment by DenhamPreen** [comment]
Looks like all the above is supported :) 
https://docs.envio.dev/docs/HyperIndex/cli-commands

- [Address](https://docs.envio.dev/docs/HyperIndex/cli-commands#envio-init-contract-import) is passed in via `-c` 
- [Api token](https://docs.envio.dev/docs/HyperIndex/cli-commands#envio-init)  `--api-token`
- [Single contract](https://docs.envio.dev/docs/HyperIndex/cli-commands#envio-init-contract-import) `--single-contract` as a bool

Here's the section in the code where you can check yourself
https://github.com/enviodev/hyperindex/blob/main/codegenerator/cli/src/cli_args/clap_definitions.rs
Here are the docs to clap - https://docs.rs/clap/latest/clap/
