### ISSUE TITLE
Smol bug on server notifications not showing on 2.9.0

### ISSUE THREAD

**Issue by DenhamPreen** [enviodev/hyperindex#370]
**Describe the bug**
![image](https://github.com/user-attachments/assets/325cd68f-52e5-46fd-be30-bf54b8107cac)

**To Reproduce**
`pnpm envio dev` on an indexer running envio version 2.9.0

**Local **
 - Envio version : 2.9.0

**Additional context**
- Likely issue in ui repo

**Comment by DZakh** [comment]
Fixed in https://github.com/enviodev/hyperindex/pull/367
