### ISSUE TITLE
إصلاح نظام التشغيل وتشغيل سير العمل

### ISSUE THREAD

**Issue by EitchEss** [enviodev/hyperindex#378]
**Describe the bug**

**To Reproduce**

E.g.

**Expected behavior**

**Screenshots**

**Local (please complete the following information):**
 - Envio version
 - Node version
 - pnpm version
 - Docker version (if running locally)

**Hosted Service (please complete the following information):**
 - Envio version
 - Link to the deployed indexer

**Additional context**

**Comment by JonoPrest** [comment]
Hi @EitchEss, would you be able to report your issue in English using google translate?

**Comment by JonoPrest** [comment]
> Originally, the operating system was rebuilt to rebuild the workflow and run as it was before, and I have a problem related to the issue and json احصل على Outlook لـ iOS<https://aka.ms/o0ukef>

Sorry @EitchEss I'm not understanding. Perhaps if there is an error you can share the error or you can share your indexer and describe what you expect to happen
