### ISSUE TITLE
No data coming for the Id, but when I restart I am getting the data 

### ISSUE THREAD

**Issue by ravaliGangasani** [enviodev/hyperindex#389]
I have an event with the name `NewApplication (uint256 id)[View Source]`

<img width="708" alt="Screenshot 2024-12-18 at 7 37 25 PM" src="https://github.com/user-attachments/assets/05894a2d-1c0d-4a82-9ad5-2c498a4ea6f0" />

I would like to get the application data for the `Id:1001`

But I am getting empty application state but I have the application data on the blockchain.

**Comment by ravaliGangasani** [comment]
I did following steps,

setting `application state` in the `NewApplication` event

`AgentFactory.NewApplication.handler(async ({ event, context }) => {

    let applicationId = `${event.chainId}:${event.params.id.toString}`
    const entity: AgentFactory_NewApplication = {
      id: `${event.chainId}:${event.srcAddress.toLowerCase()}:${event.params.id}`,
      event_id: event.params.id,
      address: event.srcAddress.toLowerCase(),
      chain: BigInt(event.chainId),
      createdAt: BigInt(event.block.timestamp),
      createdBlock: BigInt(event.block.number),
      logIndex: event.logIndex,
      transactionIndex: event.transaction.transactionIndex,
      txHash: event.transaction.hash,
      application_id: applicationId
    };

    context.AgentFactory_NewApplication.set(entity);

    let chainId = event.chainId
    let contractAddress = formatToAddress(event.srcAddress.toLowerCase())
    let proposalId = Number(event.params.id)
    let {application }  = await getApplication({chainId, contractAddress, proposalId})

    let applicationObj = await context.Application.get(applicationId)
    if (applicationObj === undefined){
      let applicationEntity: Application = {
        id: applicationId,
        address: event.srcAddress.toLowerCase(),
        chain: BigInt(event.chainId),
        createdAt: BigInt(event.block.timestamp),
        createdBlock: BigInt(event.block.number),
        updatedAt: BigInt(event.block.timestamp),
        updatedBlock: BigInt(event.block.number),

        cores: application.cores,
        daoThreshold: undefined,
        daoVotingPeriod: BigInt(application.daoThreshold),
        name: application.name,
        proposalEndBlock: application.proposalEndBlock,
        proposer_id: `${event.chainId}:${application.proposer}`,
        status: application.status,
        symbol: application.symbol,
        tbaImplementation: application.tbaImplementation,
        tbaSalt: application.tbaSalt,
        tokenURI: application.tokenURI,
        virtualId: application.virtualId,
        withdrawableAmount: application.withdrawableAmount
      }
      context.Application.set(applicationEntity)
    }
  
  });`
  
  I did `envio stop`, `envio codegen`, `envio dev`

**Comment by DZakh** [comment]
The `getApplication` performs the call using the viem client. I can't help with the issue, since it's not related to the indexer, and I don't have an immediate answer to the problem.

I recommend trying to log the params of the RPC call and response and perform the RPC call without a viem client in an isolated environment. 

Also, what's definitely make the debugging easier is to write tests for the handler. You can use our test framework for this https://docs.envio.dev/docs/HyperIndex/testing#writing-tests
